AR = ar
CXX = g++
CC = gcc
CXXFLAGS = -g -m32 -fpermissive -I.. -I../GENERAL -I../DATABASE -I../DRIVERS -D_BORLAND -DLEGENDAIR_S2 -I../DISPLAY -I../DRIVERS_DISPLAY -I../SYSTEM -I../DATABASE_SETTINGS -I../DRIVERS_HMI -g `pkg-config sdl --cflags`  -I../DRIVER_DISPLAY -I../TIMERS
LDFLAGS = -g -m32 -L../DATABASE -ldatabase `pkg-config sdl --libs` -lGL -lSDL_gfx  
CFLAGS =  -g -m32 -I.. -I../GENERAL -I../DATABASE -I../DRIVERS -D_BORLAND -DLEGENDAIR_S2 -I../DISPLAY -I../DRIVERS_DISPLAY -I../SYSTEM -I../DATABASE_SETTINGS -I../DRIVERS_HMI -I../SECURITY -I../MAIN -I../VENTILATION -I../EEPROM -g -I../TIMERS
