all:
	make -C DATABASE
	make -C HMI
#	make -C TIMERS
	make -C SYSTEM
	make -C DRIVERS_DISPLAY
	make -C DISPLAY

clean:
	make -C DATABASE clean
	make -C HMI clean
#	make -C TIMERS clean
	make -C SYSTEM clean
	make -C DRIVERS_DISPLAY clean
	make -C DISPLAY clean
